//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OrderTrackerv2.HOOemployees {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ShirtData : DataSet {
        
        private ShirtOrdersDataTable tableShirtOrders;
        
        public ShirtData() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ShirtData(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ShirtOrders"] != null)) {
                    this.Tables.Add(new ShirtOrdersDataTable(ds.Tables["ShirtOrders"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ShirtOrdersDataTable ShirtOrders {
            get {
                return this.tableShirtOrders;
            }
        }
        
        public override DataSet Clone() {
            ShirtData cln = ((ShirtData)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ShirtOrders"] != null)) {
                this.Tables.Add(new ShirtOrdersDataTable(ds.Tables["ShirtOrders"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableShirtOrders = ((ShirtOrdersDataTable)(this.Tables["ShirtOrders"]));
            if ((this.tableShirtOrders != null)) {
                this.tableShirtOrders.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "ShirtData";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/ShirtData.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableShirtOrders = new ShirtOrdersDataTable();
            this.Tables.Add(this.tableShirtOrders);
        }
        
        private bool ShouldSerializeShirtOrders() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ShirtOrdersRowChangeEventHandler(object sender, ShirtOrdersRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShirtOrdersDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnorderNumber;
            
            private DataColumn columnmanufacturer;
            
            private DataColumn columncolor;
            
            private DataColumn columnnum_24;
            
            private DataColumn columnnum_68;
            
            private DataColumn columnnum_1012;
            
            private DataColumn columnnum_1416;
            
            private DataColumn columnnum_s;
            
            private DataColumn columnnum_m;
            
            private DataColumn columnnum_l;
            
            private DataColumn columnnum_xl;
            
            private DataColumn columnnum_xxl;
            
            private DataColumn columnnum_xxxl;
            
            private DataColumn columnnum_xxxxl;
            
            private DataColumn columnnum_other;
            
            private DataColumn columnunitPrice;
            
            private DataColumn columnstyleNum;
            
            private DataColumn columndescription;
            
            private DataColumn columntype;
            
            private DataColumn columnsleeveOrPocket;
            
            private DataColumn columntotalQty;
            
            private DataColumn columntotalPrice;
            
            internal ShirtOrdersDataTable() : 
                    base("ShirtOrders") {
                this.InitClass();
            }
            
            internal ShirtOrdersDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn orderNumberColumn {
                get {
                    return this.columnorderNumber;
                }
            }
            
            internal DataColumn manufacturerColumn {
                get {
                    return this.columnmanufacturer;
                }
            }
            
            internal DataColumn colorColumn {
                get {
                    return this.columncolor;
                }
            }
            
            internal DataColumn num_24Column {
                get {
                    return this.columnnum_24;
                }
            }
            
            internal DataColumn num_68Column {
                get {
                    return this.columnnum_68;
                }
            }
            
            internal DataColumn num_1012Column {
                get {
                    return this.columnnum_1012;
                }
            }
            
            internal DataColumn num_1416Column {
                get {
                    return this.columnnum_1416;
                }
            }
            
            internal DataColumn num_sColumn {
                get {
                    return this.columnnum_s;
                }
            }
            
            internal DataColumn num_mColumn {
                get {
                    return this.columnnum_m;
                }
            }
            
            internal DataColumn num_lColumn {
                get {
                    return this.columnnum_l;
                }
            }
            
            internal DataColumn num_xlColumn {
                get {
                    return this.columnnum_xl;
                }
            }
            
            internal DataColumn num_xxlColumn {
                get {
                    return this.columnnum_xxl;
                }
            }
            
            internal DataColumn num_xxxlColumn {
                get {
                    return this.columnnum_xxxl;
                }
            }
            
            internal DataColumn num_xxxxlColumn {
                get {
                    return this.columnnum_xxxxl;
                }
            }
            
            internal DataColumn num_otherColumn {
                get {
                    return this.columnnum_other;
                }
            }
            
            internal DataColumn unitPriceColumn {
                get {
                    return this.columnunitPrice;
                }
            }
            
            internal DataColumn styleNumColumn {
                get {
                    return this.columnstyleNum;
                }
            }
            
            internal DataColumn descriptionColumn {
                get {
                    return this.columndescription;
                }
            }
            
            internal DataColumn typeColumn {
                get {
                    return this.columntype;
                }
            }
            
            internal DataColumn sleeveOrPocketColumn {
                get {
                    return this.columnsleeveOrPocket;
                }
            }
            
            internal DataColumn totalQtyColumn {
                get {
                    return this.columntotalQty;
                }
            }
            
            internal DataColumn totalPriceColumn {
                get {
                    return this.columntotalPrice;
                }
            }
            
            public ShirtOrdersRow this[int index] {
                get {
                    return ((ShirtOrdersRow)(this.Rows[index]));
                }
            }
            
            public event ShirtOrdersRowChangeEventHandler ShirtOrdersRowChanged;
            
            public event ShirtOrdersRowChangeEventHandler ShirtOrdersRowChanging;
            
            public event ShirtOrdersRowChangeEventHandler ShirtOrdersRowDeleted;
            
            public event ShirtOrdersRowChangeEventHandler ShirtOrdersRowDeleting;
            
            public void AddShirtOrdersRow(ShirtOrdersRow row) {
                this.Rows.Add(row);
            }
            
            public ShirtOrdersRow AddShirtOrdersRow(
                        int orderNumber, 
                        string manufacturer, 
                        string color, 
                        int num_24, 
                        int num_68, 
                        int num_1012, 
                        int num_1416, 
                        int num_s, 
                        int num_m, 
                        int num_l, 
                        int num_xl, 
                        int num_xxl, 
                        int num_xxxl, 
                        int num_xxxxl, 
                        int num_other, 
                        System.Decimal unitPrice, 
                        string styleNum, 
                        string description, 
                        string type, 
                        string sleeveOrPocket, 
                        int totalQty, 
                        System.Decimal totalPrice) {
                ShirtOrdersRow rowShirtOrdersRow = ((ShirtOrdersRow)(this.NewRow()));
                rowShirtOrdersRow.ItemArray = new object[] {
                        orderNumber,
                        manufacturer,
                        color,
                        num_24,
                        num_68,
                        num_1012,
                        num_1416,
                        num_s,
                        num_m,
                        num_l,
                        num_xl,
                        num_xxl,
                        num_xxxl,
                        num_xxxxl,
                        num_other,
                        unitPrice,
                        styleNum,
                        description,
                        type,
                        sleeveOrPocket,
                        totalQty,
                        totalPrice};
                this.Rows.Add(rowShirtOrdersRow);
                return rowShirtOrdersRow;
            }
            
            public ShirtOrdersRow FindByorderNumbermanufacturercolor(int orderNumber, string manufacturer, string color) {
                return ((ShirtOrdersRow)(this.Rows.Find(new object[] {
                            orderNumber,
                            manufacturer,
                            color})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ShirtOrdersDataTable cln = ((ShirtOrdersDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ShirtOrdersDataTable();
            }
            
            internal void InitVars() {
                this.columnorderNumber = this.Columns["orderNumber"];
                this.columnmanufacturer = this.Columns["manufacturer"];
                this.columncolor = this.Columns["color"];
                this.columnnum_24 = this.Columns["num_24"];
                this.columnnum_68 = this.Columns["num_68"];
                this.columnnum_1012 = this.Columns["num_1012"];
                this.columnnum_1416 = this.Columns["num_1416"];
                this.columnnum_s = this.Columns["num_s"];
                this.columnnum_m = this.Columns["num_m"];
                this.columnnum_l = this.Columns["num_l"];
                this.columnnum_xl = this.Columns["num_xl"];
                this.columnnum_xxl = this.Columns["num_xxl"];
                this.columnnum_xxxl = this.Columns["num_xxxl"];
                this.columnnum_xxxxl = this.Columns["num_xxxxl"];
                this.columnnum_other = this.Columns["num_other"];
                this.columnunitPrice = this.Columns["unitPrice"];
                this.columnstyleNum = this.Columns["styleNum"];
                this.columndescription = this.Columns["description"];
                this.columntype = this.Columns["type"];
                this.columnsleeveOrPocket = this.Columns["sleeveOrPocket"];
                this.columntotalQty = this.Columns["totalQty"];
                this.columntotalPrice = this.Columns["totalPrice"];
            }
            
            private void InitClass() {
                this.columnorderNumber = new DataColumn("orderNumber", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnorderNumber);
                this.columnmanufacturer = new DataColumn("manufacturer", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmanufacturer);
                this.columncolor = new DataColumn("color", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncolor);
                this.columnnum_24 = new DataColumn("num_24", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_24);
                this.columnnum_68 = new DataColumn("num_68", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_68);
                this.columnnum_1012 = new DataColumn("num_1012", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_1012);
                this.columnnum_1416 = new DataColumn("num_1416", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_1416);
                this.columnnum_s = new DataColumn("num_s", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_s);
                this.columnnum_m = new DataColumn("num_m", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_m);
                this.columnnum_l = new DataColumn("num_l", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_l);
                this.columnnum_xl = new DataColumn("num_xl", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_xl);
                this.columnnum_xxl = new DataColumn("num_xxl", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_xxl);
                this.columnnum_xxxl = new DataColumn("num_xxxl", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_xxxl);
                this.columnnum_xxxxl = new DataColumn("num_xxxxl", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_xxxxl);
                this.columnnum_other = new DataColumn("num_other", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_other);
                this.columnunitPrice = new DataColumn("unitPrice", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnunitPrice);
                this.columnstyleNum = new DataColumn("styleNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstyleNum);
                this.columndescription = new DataColumn("description", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescription);
                this.columntype = new DataColumn("type", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntype);
                this.columnsleeveOrPocket = new DataColumn("sleeveOrPocket", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnsleeveOrPocket);
                this.columntotalQty = new DataColumn("totalQty", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntotalQty);
                this.columntotalPrice = new DataColumn("totalPrice", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntotalPrice);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnorderNumber,
                                this.columnmanufacturer,
                                this.columncolor}, true));
                this.columnorderNumber.AllowDBNull = false;
                this.columnmanufacturer.AllowDBNull = false;
                this.columncolor.AllowDBNull = false;
                this.columnnum_24.AllowDBNull = false;
                this.columnnum_68.AllowDBNull = false;
                this.columnnum_1012.AllowDBNull = false;
                this.columnnum_1416.AllowDBNull = false;
                this.columnnum_s.AllowDBNull = false;
                this.columnnum_m.AllowDBNull = false;
                this.columnnum_l.AllowDBNull = false;
                this.columnnum_xl.AllowDBNull = false;
                this.columnnum_xxl.AllowDBNull = false;
                this.columnnum_xxxl.AllowDBNull = false;
                this.columnnum_xxxxl.AllowDBNull = false;
                this.columnnum_other.AllowDBNull = false;
                this.columnunitPrice.AllowDBNull = false;
                this.columntype.AllowDBNull = false;
                this.columnsleeveOrPocket.AllowDBNull = false;
                this.columntotalQty.ReadOnly = true;
                this.columntotalPrice.ReadOnly = true;
            }
            
            public ShirtOrdersRow NewShirtOrdersRow() {
                return ((ShirtOrdersRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ShirtOrdersRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ShirtOrdersRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ShirtOrdersRowChanged != null)) {
                    this.ShirtOrdersRowChanged(this, new ShirtOrdersRowChangeEvent(((ShirtOrdersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ShirtOrdersRowChanging != null)) {
                    this.ShirtOrdersRowChanging(this, new ShirtOrdersRowChangeEvent(((ShirtOrdersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ShirtOrdersRowDeleted != null)) {
                    this.ShirtOrdersRowDeleted(this, new ShirtOrdersRowChangeEvent(((ShirtOrdersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ShirtOrdersRowDeleting != null)) {
                    this.ShirtOrdersRowDeleting(this, new ShirtOrdersRowChangeEvent(((ShirtOrdersRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveShirtOrdersRow(ShirtOrdersRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShirtOrdersRow : DataRow {
            
            private ShirtOrdersDataTable tableShirtOrders;
            
            internal ShirtOrdersRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableShirtOrders = ((ShirtOrdersDataTable)(this.Table));
            }
            
            public int orderNumber {
                get {
                    return ((int)(this[this.tableShirtOrders.orderNumberColumn]));
                }
                set {
                    this[this.tableShirtOrders.orderNumberColumn] = value;
                }
            }
            
            public string manufacturer {
                get {
                    return ((string)(this[this.tableShirtOrders.manufacturerColumn]));
                }
                set {
                    this[this.tableShirtOrders.manufacturerColumn] = value;
                }
            }
            
            public string color {
                get {
                    return ((string)(this[this.tableShirtOrders.colorColumn]));
                }
                set {
                    this[this.tableShirtOrders.colorColumn] = value;
                }
            }
            
            public int num_24 {
                get {
                    return ((int)(this[this.tableShirtOrders.num_24Column]));
                }
                set {
                    this[this.tableShirtOrders.num_24Column] = value;
                }
            }
            
            public int num_68 {
                get {
                    return ((int)(this[this.tableShirtOrders.num_68Column]));
                }
                set {
                    this[this.tableShirtOrders.num_68Column] = value;
                }
            }
            
            public int num_1012 {
                get {
                    return ((int)(this[this.tableShirtOrders.num_1012Column]));
                }
                set {
                    this[this.tableShirtOrders.num_1012Column] = value;
                }
            }
            
            public int num_1416 {
                get {
                    return ((int)(this[this.tableShirtOrders.num_1416Column]));
                }
                set {
                    this[this.tableShirtOrders.num_1416Column] = value;
                }
            }
            
            public int num_s {
                get {
                    return ((int)(this[this.tableShirtOrders.num_sColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_sColumn] = value;
                }
            }
            
            public int num_m {
                get {
                    return ((int)(this[this.tableShirtOrders.num_mColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_mColumn] = value;
                }
            }
            
            public int num_l {
                get {
                    return ((int)(this[this.tableShirtOrders.num_lColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_lColumn] = value;
                }
            }
            
            public int num_xl {
                get {
                    return ((int)(this[this.tableShirtOrders.num_xlColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_xlColumn] = value;
                }
            }
            
            public int num_xxl {
                get {
                    return ((int)(this[this.tableShirtOrders.num_xxlColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_xxlColumn] = value;
                }
            }
            
            public int num_xxxl {
                get {
                    return ((int)(this[this.tableShirtOrders.num_xxxlColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_xxxlColumn] = value;
                }
            }
            
            public int num_xxxxl {
                get {
                    return ((int)(this[this.tableShirtOrders.num_xxxxlColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_xxxxlColumn] = value;
                }
            }
            
            public int num_other {
                get {
                    return ((int)(this[this.tableShirtOrders.num_otherColumn]));
                }
                set {
                    this[this.tableShirtOrders.num_otherColumn] = value;
                }
            }
            
            public System.Decimal unitPrice {
                get {
                    return ((System.Decimal)(this[this.tableShirtOrders.unitPriceColumn]));
                }
                set {
                    this[this.tableShirtOrders.unitPriceColumn] = value;
                }
            }
            
            public string styleNum {
                get {
                    try {
                        return ((string)(this[this.tableShirtOrders.styleNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShirtOrders.styleNumColumn] = value;
                }
            }
            
            public string description {
                get {
                    try {
                        return ((string)(this[this.tableShirtOrders.descriptionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShirtOrders.descriptionColumn] = value;
                }
            }
            
            public string type {
                get {
                    return ((string)(this[this.tableShirtOrders.typeColumn]));
                }
                set {
                    this[this.tableShirtOrders.typeColumn] = value;
                }
            }
            
            public string sleeveOrPocket {
                get {
                    return ((string)(this[this.tableShirtOrders.sleeveOrPocketColumn]));
                }
                set {
                    this[this.tableShirtOrders.sleeveOrPocketColumn] = value;
                }
            }
            
            public int totalQty {
                get {
                    try {
                        return ((int)(this[this.tableShirtOrders.totalQtyColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShirtOrders.totalQtyColumn] = value;
                }
            }
            
            public System.Decimal totalPrice {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableShirtOrders.totalPriceColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShirtOrders.totalPriceColumn] = value;
                }
            }
            
            public bool IsstyleNumNull() {
                return this.IsNull(this.tableShirtOrders.styleNumColumn);
            }
            
            public void SetstyleNumNull() {
                this[this.tableShirtOrders.styleNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsdescriptionNull() {
                return this.IsNull(this.tableShirtOrders.descriptionColumn);
            }
            
            public void SetdescriptionNull() {
                this[this.tableShirtOrders.descriptionColumn] = System.Convert.DBNull;
            }
            
            public bool IstotalQtyNull() {
                return this.IsNull(this.tableShirtOrders.totalQtyColumn);
            }
            
            public void SettotalQtyNull() {
                this[this.tableShirtOrders.totalQtyColumn] = System.Convert.DBNull;
            }
            
            public bool IstotalPriceNull() {
                return this.IsNull(this.tableShirtOrders.totalPriceColumn);
            }
            
            public void SettotalPriceNull() {
                this[this.tableShirtOrders.totalPriceColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShirtOrdersRowChangeEvent : EventArgs {
            
            private ShirtOrdersRow eventRow;
            
            private DataRowAction eventAction;
            
            public ShirtOrdersRowChangeEvent(ShirtOrdersRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ShirtOrdersRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
