//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OrderTrackerv2.HOOemployees {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class SpeedData : DataSet {
        
        private SpeedDataTable tableSpeed;
        
        public SpeedData() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected SpeedData(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Speed"] != null)) {
                    this.Tables.Add(new SpeedDataTable(ds.Tables["Speed"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SpeedDataTable Speed {
            get {
                return this.tableSpeed;
            }
        }
        
        public override DataSet Clone() {
            SpeedData cln = ((SpeedData)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Speed"] != null)) {
                this.Tables.Add(new SpeedDataTable(ds.Tables["Speed"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSpeed = ((SpeedDataTable)(this.Tables["Speed"]));
            if ((this.tableSpeed != null)) {
                this.tableSpeed.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "SpeedData";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/SpeedData.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSpeed = new SpeedDataTable();
            this.Tables.Add(this.tableSpeed);
        }
        
        private bool ShouldSerializeSpeed() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void SpeedRowChangeEventHandler(object sender, SpeedRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SpeedDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnSpeed;
            
            internal SpeedDataTable() : 
                    base("Speed") {
                this.InitClass();
            }
            
            internal SpeedDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn SpeedColumn {
                get {
                    return this.columnSpeed;
                }
            }
            
            public SpeedRow this[int index] {
                get {
                    return ((SpeedRow)(this.Rows[index]));
                }
            }
            
            public event SpeedRowChangeEventHandler SpeedRowChanged;
            
            public event SpeedRowChangeEventHandler SpeedRowChanging;
            
            public event SpeedRowChangeEventHandler SpeedRowDeleted;
            
            public event SpeedRowChangeEventHandler SpeedRowDeleting;
            
            public void AddSpeedRow(SpeedRow row) {
                this.Rows.Add(row);
            }
            
            public SpeedRow AddSpeedRow(string Speed) {
                SpeedRow rowSpeedRow = ((SpeedRow)(this.NewRow()));
                rowSpeedRow.ItemArray = new object[] {
                        Speed};
                this.Rows.Add(rowSpeedRow);
                return rowSpeedRow;
            }
            
            public SpeedRow FindBySpeed(string Speed) {
                return ((SpeedRow)(this.Rows.Find(new object[] {
                            Speed})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                SpeedDataTable cln = ((SpeedDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new SpeedDataTable();
            }
            
            internal void InitVars() {
                this.columnSpeed = this.Columns["Speed"];
            }
            
            private void InitClass() {
                this.columnSpeed = new DataColumn("Speed", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSpeed);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnSpeed}, true));
                this.columnSpeed.AllowDBNull = false;
                this.columnSpeed.Unique = true;
            }
            
            public SpeedRow NewSpeedRow() {
                return ((SpeedRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new SpeedRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SpeedRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SpeedRowChanged != null)) {
                    this.SpeedRowChanged(this, new SpeedRowChangeEvent(((SpeedRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SpeedRowChanging != null)) {
                    this.SpeedRowChanging(this, new SpeedRowChangeEvent(((SpeedRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SpeedRowDeleted != null)) {
                    this.SpeedRowDeleted(this, new SpeedRowChangeEvent(((SpeedRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SpeedRowDeleting != null)) {
                    this.SpeedRowDeleting(this, new SpeedRowChangeEvent(((SpeedRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSpeedRow(SpeedRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SpeedRow : DataRow {
            
            private SpeedDataTable tableSpeed;
            
            internal SpeedRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSpeed = ((SpeedDataTable)(this.Table));
            }
            
            public string Speed {
                get {
                    return ((string)(this[this.tableSpeed.SpeedColumn]));
                }
                set {
                    this[this.tableSpeed.SpeedColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SpeedRowChangeEvent : EventArgs {
            
            private SpeedRow eventRow;
            
            private DataRowAction eventAction;
            
            public SpeedRowChangeEvent(SpeedRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SpeedRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
