//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OrderTrackerv2.Customers {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class OrderTypes : DataSet {
        
        private orderTypesDataTable tableorderTypes;
        
        public OrderTypes() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected OrderTypes(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["orderTypes"] != null)) {
                    this.Tables.Add(new orderTypesDataTable(ds.Tables["orderTypes"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public orderTypesDataTable orderTypes {
            get {
                return this.tableorderTypes;
            }
        }
        
        public override DataSet Clone() {
            OrderTypes cln = ((OrderTypes)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["orderTypes"] != null)) {
                this.Tables.Add(new orderTypesDataTable(ds.Tables["orderTypes"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableorderTypes = ((orderTypesDataTable)(this.Tables["orderTypes"]));
            if ((this.tableorderTypes != null)) {
                this.tableorderTypes.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "OrderTypes";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/OrderTypes.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableorderTypes = new orderTypesDataTable();
            this.Tables.Add(this.tableorderTypes);
        }
        
        private bool ShouldSerializeorderTypes() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void orderTypesRowChangeEventHandler(object sender, orderTypesRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class orderTypesDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnType;
            
            internal orderTypesDataTable() : 
                    base("orderTypes") {
                this.InitClass();
            }
            
            internal orderTypesDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn TypeColumn {
                get {
                    return this.columnType;
                }
            }
            
            public orderTypesRow this[int index] {
                get {
                    return ((orderTypesRow)(this.Rows[index]));
                }
            }
            
            public event orderTypesRowChangeEventHandler orderTypesRowChanged;
            
            public event orderTypesRowChangeEventHandler orderTypesRowChanging;
            
            public event orderTypesRowChangeEventHandler orderTypesRowDeleted;
            
            public event orderTypesRowChangeEventHandler orderTypesRowDeleting;
            
            public void AddorderTypesRow(orderTypesRow row) {
                this.Rows.Add(row);
            }
            
            public orderTypesRow AddorderTypesRow(string Type) {
                orderTypesRow roworderTypesRow = ((orderTypesRow)(this.NewRow()));
                roworderTypesRow.ItemArray = new object[] {
                        Type};
                this.Rows.Add(roworderTypesRow);
                return roworderTypesRow;
            }
            
            public orderTypesRow FindByType(string Type) {
                return ((orderTypesRow)(this.Rows.Find(new object[] {
                            Type})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                orderTypesDataTable cln = ((orderTypesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new orderTypesDataTable();
            }
            
            internal void InitVars() {
                this.columnType = this.Columns["Type"];
            }
            
            private void InitClass() {
                this.columnType = new DataColumn("Type", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnType);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnType}, true));
                this.columnType.AllowDBNull = false;
                this.columnType.Unique = true;
            }
            
            public orderTypesRow NeworderTypesRow() {
                return ((orderTypesRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new orderTypesRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(orderTypesRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.orderTypesRowChanged != null)) {
                    this.orderTypesRowChanged(this, new orderTypesRowChangeEvent(((orderTypesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.orderTypesRowChanging != null)) {
                    this.orderTypesRowChanging(this, new orderTypesRowChangeEvent(((orderTypesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.orderTypesRowDeleted != null)) {
                    this.orderTypesRowDeleted(this, new orderTypesRowChangeEvent(((orderTypesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.orderTypesRowDeleting != null)) {
                    this.orderTypesRowDeleting(this, new orderTypesRowChangeEvent(((orderTypesRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveorderTypesRow(orderTypesRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class orderTypesRow : DataRow {
            
            private orderTypesDataTable tableorderTypes;
            
            internal orderTypesRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableorderTypes = ((orderTypesDataTable)(this.Table));
            }
            
            public string Type {
                get {
                    return ((string)(this[this.tableorderTypes.TypeColumn]));
                }
                set {
                    this[this.tableorderTypes.TypeColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class orderTypesRowChangeEvent : EventArgs {
            
            private orderTypesRow eventRow;
            
            private DataRowAction eventAction;
            
            public orderTypesRowChangeEvent(orderTypesRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public orderTypesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
